### ISSUE TITLE
menu_key rebinding ignored

### ISSUE THREAD

**Issue by qdii** [kiddos/gemini.nvim#7]
I set up this config:
```
  { 'kiddos/gemini.nvim',
    build = { 'pip install -r requirements.txt', ':UpdateRemotePlugins' },
    config = function()
      require('gemini').setup {
        menu_key = '<C-g>'
      }
    end
  },
```

Yet `C-o` is still triggering the menu

**Comment by kiddos** [comment]
see if [this](https://github.com/kiddos/gemini.nvim/commit/d831e0f61bb84daecfc76d99b4d992bab5eb4260) fix it.

**Comment by qdii** [comment]
It looks like this is indeed fixed! Thank you :)
