### ISSUE TITLE
Please change default ctrl-o for the menu

### ISSUE THREAD

**Issue by kompadre** [kiddos/gemini.nvim#8]
Hi there. Thanks for this great plugin! I think both Gemini and it's usage as code assistant is very understated. 
Now there's something that rubbed me the wrong way: the use of Ctrl+o to show Gemini menu, something I had to remap immediatly. I and many other people use it to "Jump Back". In fact it's one of the actions I use the most. I know it's not a bug yet it's a configuration that usurps one of the most used key combinations . Thanks.

**Comment by kiddos** [comment]
I actually forgot about this mapping. [bfd3195](https://github.com/kiddos/gemini.nvim/commit/bfd31950db3861d6a711125a379fea38405c819c)

**Comment by kompadre** [comment]
Thanks so much mate! That was incredibly fast.
